spring:
  application:
    name: viaborders-service

  logging:
    level:
      # ------------------------------------------------------------------------------------------------------------------
      # Application
      # ------------------------------------------------------------------------------------------------------------------

      # noinspection SpringBootApplicationYaml
      org.viaborders: DEBUG

      # ------------------------------------------------------------------------------------------------------------------
      # Spring Boot, Spring Framework
      # ------------------------------------------------------------------------------------------------------------------

      # Log HTTP method, URL path, query parameters, returned HTTP status code
      # noinspection SpringBootApplicationYaml
      org.springframework.web.servlet.DispatcherServlet: DEBUG