spring:
  application:
    name: viaborders-service

  http:
    # ------------------------------------------------------------------------------------------------------------------
    # HTTP Clients
    # ------------------------------------------------------------------------------------------------------------------
    clients:
      connect-timeout: 5s
      read-timeout: 3s
      redirects: dont_follow

  logging:
    level:
      # ----------------------------------------------------------------------------------------------------------------
      # Application
      # ----------------------------------------------------------------------------------------------------------------

      # noinspection SpringBootApplicationYaml
      org.viaborders: DEBUG

      # ----------------------------------------------------------------------------------------------------------------
      # Spring Boot, Spring Framework
      # ----------------------------------------------------------------------------------------------------------------

      # Log HTTP method, URL path, query parameters, returned HTTP status code
      # noinspection SpringBootApplicationYaml
      org.springframework.web.servlet.DispatcherServlet: DEBUG