# ----------------------------------------------------------------------------------------------------------------------
# Spring Boot configuration
# ----------------------------------------------------------------------------------------------------------------------
spring:
  application:
    name: viaborders-service-1.0.0-SNAPSHOT

  http:
    # ------------------------------------------------------------------------------------------------------------------
    # HTTP Clients
    # ------------------------------------------------------------------------------------------------------------------
    clients:
      connect-timeout: 5s
      read-timeout: 4s
      redirects: dont_follow

  output:
    ansi:
      enabled: always

  web:
    # TODO: 2026-07-03: TOKU: Disable in production.
    error:
      include-binding-errors: always
      include-exception: true
      include-message: always
      include-path: always
      include-stacktrace: never
      whitelabel:
        enabled: true


# ----------------------------------------------------------------------------------------------------------------------
# Log configuration
# ----------------------------------------------------------------------------------------------------------------------
logging:
  level:
    # ----------------------------------------------------------------------------------------------------------------
    # Application
    # ----------------------------------------------------------------------------------------------------------------

    # noinspection SpringBootApplicationYaml
    org.viaborders: TRACE

    # ----------------------------------------------------------------------------------------------------------------
    # Spring Boot, Spring Framework
    # ----------------------------------------------------------------------------------------------------------------

    # Log HTTP method, URL path, query parameters, returned HTTP status code
    # noinspection SpringBootApplicationYaml
    org.springframework.web.servlet.DispatcherServlet: DEBUG


# ----------------------------------------------------------------------------------------------------------------------
# Custom, application logic related configuration
# ----------------------------------------------------------------------------------------------------------------------
viaborders:
  countries-rest-service:
    # World countries REST service - JSON resource URL
    url-json: https://raw.githubusercontent.com/mledoze/countries/master/countries.json